### ISSUE TITLE
Default path results in blank page

### ISSUE THREAD

**Issue by cederstrom** [jsakamoto/BlazingStory#12]
Hi,

I have tried to run the sample app in this repo and create a new project from the template but both result in loading indicator and then a blank page.

This example is from a test project where I created a first sample story but it looks the same even with a new, clean project:

https://github.com/jsakamoto/BlazingStory/assets/1394520/d1b4c18a-2ba3-4fae-a011-1c845bd504e7

As you can see, when I edit the query to be a path the app loads as expected.

Any thought on what might be wrong?

Tested on MacBook Pro (M1 Max) with .NET 7.

**Comment by cederstrom** [comment]
Good thing that it was not just on my machine! I forgot to mention (but you figured it out) that I tested in Firefox.

Let me know if I can be of any assistance :)

**Comment by jsakamoto** [comment]
@cederstrom I released the new version of Blazing Story today.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.14#release-body-tab

This version is fixed the issue you reported. Please check it out.

And please let me say again that thank you for your contributions!👍
