### ISSUE TITLE
Visual Studio v17.6.0 Preview 5.0

### ISSUE THREAD

**Issue by JeepNL** [jsakamoto/BlazingStory#2]
Using Visual Studio v17.6.0 Preview 5.0
SDK Installed: .NET 8 preview 3

When I install the template with `dotnet new install BlazingStory.ProjectTemplates` (that works) it doesn't show up in the 'FILE' -> 'NEW' -> 'PROJECT' list.

I closed Visuals Studio before installing the template.

When I try to use the CLI you've a typo in your README.md: 

`dotnet new blazingstory -n MyRazorClassLib.Stories` should be

`dotnet new blazingstorywasm -n MyRazorClassLib.Stories`

But when I try to execute `dotnet sln add ./MyRazorClassLib.Stories/` I'm getting the error:

'Specified solution file C:\X\Repos\Test\ does not exist, or there is no solution file in the directory.' [edit]

**Comment by jsakamoto** [comment]
@JeepNL  Thank you for your feedback! 

I'm not sure why the "Blazing Story" project template did not appear in your Visual Studio at this time. I'll investigate it later.

Thank you for reporting the typo in README. I'll fix it and republish the NuGet package as soon as possible.

> But when I try to execute dotnet sln add ./MyRazorClassLib.Stories/ I'm getting the error

The README confused you. It is my fault. Actually, In this section, there is a pre-requirement that there is already a solution file (.sln) in the current directory with a pre-exists Razor class library project.

So if you want to launch the Blazing Story app immediately by dotnet CLI, you don't have to do that. Just do the `dotnet run --project .\MyRazorClassLib.Stories\` command.

Again, thank you for your feedback! Your feedback will save time for so many developers. I'll let you know when I get a progress.

**Comment by jsakamoto** [comment]
@JeepNL I have released the new version, v.1.0.0-preview.3.1, which includes fixing the problem of the README you reported. You can see all of the changes on this version in the release notes from [here](https://github.com/jsakamoto/BlazingStory/blob/main/RELEASE-NOTES.txt).

By the way, I've not succeeded in reproducing the problem that the project template would not appear in Visual Studio's "Create a new project" dialog still now. So may I have more details from you, such as the version of Visual Studio (ex. "Visual Studio 2022 Enterprise, Version.17.4.0") or some screenshots of the "Create a new project" dialog?

**Comment by JeepNL** [comment]
**I'm using:** 

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 6.0

which you can download here: https://visualstudio.microsoft.com/vs/preview/

## Screenshots (4):
(FYI: i've looked through all the templates, it isn't there.)

### 1/4 Installing 'BlazingStories.ProjectTemplates'

![Screenshot 2023-05-03 134444](https://user-images.githubusercontent.com/39458532/235908855-46527136-1eec-4961-bead-51b4970ee6cd.png)

### 2/4 New 'blazingstorywasm'

![Screenshot 2023-05-03 134644](https://user-images.githubusercontent.com/39458532/235908881-547c1d8e-b2f4-45b8-8deb-739f8b57bfa2.png)

### 3/4 New project in Visual Studio, search term 'blaz'

![Screenshot 2023-05-03 134148](https://user-images.githubusercontent.com/39458532/235908939-2e5aba2a-13f6-44f1-910f-f48e51dd8631.png)

### 4/4 New project in Visual Studio, search term 'blazing'

![Screenshot 2023-05-03 134326](https://user-images.githubusercontent.com/39458532/235908970-afa22f95-0993-435a-890f-235ea856330a.png)

**Comment by jsakamoto** [comment]
@JeepNL Thank you for providing me with such detailed reports! The screenshots you shared are especially helpful, and I appreciate your effort. I'll be looking into the issue you reported.

By the way, I realized that I forgot to ask you what .NET SDK versions are installed in your development environment. Sorry to bother you, but would you mind sharing the results of the `dotnet --info` command execution?

Thank you for your cooperation.

**Comment by JeepNL** [comment]
I've only The .NET SDK 8 preview 3 installed and the workloads: `wasm-tools` and `wasm-experimental`

![Screenshot 2023-05-03 170100](https://user-images.githubusercontent.com/39458532/235956584-eec68535-b435-48bb-a91b-41cedb5a95da.png)

**Comment by jsakamoto** [comment]
@JeepNL Thanks to the information you provided, I found that the project template didn't support .NET 8 correctly, so I fixed that point and published it.

I believe that you will see the project template for the "Blazing Story" in your Visual Studio's "Create a new project" dialog after you re-install the project template as the following command line.

```
dotnet new install BlazingStory.ProjectTemplates
```

**Comment by JeepNL** [comment]
Yup! It's now in the new project list. I'm glad I could help a bit and thank you for fixing it! 

### Screenshot:

![blazing](https://user-images.githubusercontent.com/39458532/236132475-0bdfa52c-ff90-42ca-b461-a6369e524c3d.png)

**Comment by jsakamoto** [comment]
@JeepNL I'm happy to hear that. 😊
Again, thank you for sharing your feedback! Your contribution was definitely helpful to other developers.👍
