### ISSUE TITLE
xml summary not inherited from parent class properties

### ISSUE THREAD

**Issue by Dovrol** [jsakamoto/BlazingStory#22]
Xml summaries does not get populated on control panel if those are properties from parent class.
![Screenshot 2024-02-10 at 08 59 11](https://github.com/jsakamoto/BlazingStory/assets/16240166/4648411c-9ca3-4250-a6d4-8d66e2c0b296)
![Screenshot 2024-02-10 at 09 02 26](https://github.com/jsakamoto/BlazingStory/assets/16240166/fbbd0e53-74a7-4d32-b204-1a5be39b3f8a)

**Comment by jsakamoto** [comment]
@Dovrol Oh... that's right, it's a lack of consideration for that scenario. Resolving problems with document inheritance can be challenging, but I'll try to fix this issue.

**Comment by Dovrol** [comment]
No pressure :) Just playing with this amazing project, and trying to help with finding some of the "bugs" :)

**Comment by jsakamoto** [comment]
Hi @Dovrol,
I believe that I resolved this issue. Could you check out the latest version, preview 23, of the "Blazing Story"?

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.23#releasenotes-body-tab

Thanks!

**Comment by Dovrol** [comment]
@jsakamoto fix, worked perfectly, although there might be one more slight improvement - support for links created with see tag.
Currently see tag is rendering just quotes instead of defined link example:
<img width="1094" alt="Screenshot 2024-02-11 at 17 29 21" src="https://github.com/jsakamoto/BlazingStory/assets/16240166/c432a9c1-7ebb-453f-aced-61286fbad426">

<img width="1145" alt="Screenshot 2024-02-11 at 17 30 51" src="https://github.com/jsakamoto/BlazingStory/assets/16240166/17d35695-a1ef-41ed-8eae-fe46ad6dca56">

**Comment by jsakamoto** [comment]
@Dovrol 
Thank you for your proposal again!
I have added support for the `<see href>` markup in XML Document Comments in the new version of the Blazing Story.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.24

Please try it out!

**Comment by Dovrol** [comment]
Great ! Thank you for your quick responses :)
