### ISSUE TITLE
Support for nullable enums

### ISSUE THREAD

**Issue by Dovrol** [jsakamoto/BlazingStory#23]
After making property of type enum nullable, control panel is displaying "-", instead of enum items (I guess in this case it also should display button to clear value or just add "null" to options).
<img width="1015" alt="Screenshot 2024-02-17 at 22 36 37" src="https://github.com/jsakamoto/BlazingStory/assets/16240166/ce1e5a25-289b-42d3-8269-d4c3ad3ab7d0">

**Comment by Dovrol** [comment]
This also applies to bool, int and other numeric types

**Comment by jsakamoto** [comment]
@Dovrol Thank you for your proposal. The latest "Blazing Story" version now supports `Nullable<T>` types for `enum`, `int`, and `bool` types.

https://www.nuget.org/packages/BlazingStory/1.0.0-preview.26#releasenotes-body-tab

Please check it out ;)

**Comment by Dovrol** [comment]
Thank you for the fix, there was small typo that "Unknown" word was rendering instead of "-" but I see that you already fixed that, so I'm closing issue :)

**Comment by jsakamoto** [comment]
> there was small typo that "Unknown" word was rendering instead of "-"

Thank you for letting me know that, @Dovrol !

I fixed it and released the new version.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.27#releasenotes-body-tab

Thank you for your contributions!
