### ISSUE TITLE
Question about default value 

### ISSUE THREAD

**Issue by nekrasov-andrii** [jsakamoto/BlazingStory#27]
Hi,
Thank you very much for a great application!

I noticed that the Default Value column is always empty.
Is it possible to fill it out?

Kind regards, Andrii.

![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/ec1058a1-cae4-408a-9b17-4d3d0c717369)

**Comment by jsakamoto** [comment]
Hi @nekrasov-andrii,
Thank you for your feedback!

Unfortunately, I've never implemented it yet.

https://github.com/jsakamoto/BlazingStory/blob/main/BlazingStory/Internals/Pages/Canvas/Controls/ControlsPanel.razor#L53

I'm considering using the `Default` parameter of the `<ArgType>` component to show default values in the control panel, like below:

```html
@attribute [Stories("...")]

<Stories TComponent="Button">
    <ArgType For="_ => _.Color" Default='"royalblue"' />
    <ArgType For="_ => _.Size" Default="ButtonSize.Middle" />
    ...
</Stories>
```

https://github.com/jsakamoto/BlazingStory/blob/main/BlazingStory/Components/ArgType.razor#L16

However, this method requires us to describe a default value for all parameters on the component manually, which must be annoying. Therefore, I want to find another way. That means I'll try to find a way for Blazing Story to automatically detect parameter default values.

**Comment by nekrasov-andrii** [comment]
Hi @jsakamoto,
Thanks for the quick response.
You're right, manually filling in the default value will be really annoying)
At the moment this is not critical for me.
But if this is implemented, it will be great!
Thank you for making a great product.
