### ISSUE TITLE
Question about "Parameter type" values

### ISSUE THREAD

**Issue by nekrasov-andrii** [jsakamoto/BlazingStory#28]
Hi,
I use RemixIcon in the my component.
The "Description" column displays all available values of this type, it's a lot to read.
Is it possible to programmatically limit the output of only a type without its values, or a limited number of records?

Kind regards, Andrii.

![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/18ddbe7b-96a0-4ff8-9dc9-f7ce463f1f8e)

**Comment by jsakamoto** [comment]
Oh my...

Thanks, @nekrasov-andrii, for your feedback. I'll try to come up with ideas to resolve this problem. But since this is my hobby product and I only have a little time to spend on it, it might take longer than you expect. I appreciate your patience.

**Comment by nekrasov-andrii** [comment]
Hi @jsakamoto,
I'm new to "BlazingStory", so a lot of things are still unclear to me.
Since this is not yet implemented out of the box,
I can offer you a workaround using css.

Need to add the following block with styles to the head tag in the "IndexPage.razor".

![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/969b6b88-0487-4fde-9f7b-a0c3d71778cd)

Result:
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/4736405f-b8ac-4405-aa66-2a682be0246e)

 Kind regards, Andrii.
