### ISSUE TITLE
Question about dark theme

### ISSUE THREAD

**Issue by nekrasov-andrii** [jsakamoto/BlazingStory#29]
Hi @jsakamoto,

In my application, I use the ThemeService service to switch themes.
For a dark theme via js, I add the class “dark” to the “body” tag, and the variables for the css are registered for the “body.dark” rule.
I tried to add the same functionality for displaying components in "BlazingStory", but nothing worked.

Is it possible to add your own classes for the "body" tag?

Could you provide an example?

Or give advice on what direction to look in?

Kind regards, Andrii.

**Comment by jsakamoto** [comment]
Hi @nekrasov-andrii,
Thank you for the good question! By the way, could you explain your requirements in more detail? For example, which areas do you want to control the theme in?

![image](https://github.com/jsakamoto/BlazingStory/assets/95908/f510a014-547f-4f04-853b-900bf6d9d256)

And who or what will trigger adding the "dark" CSS class to the `<body>` tag in your possible scenario? If you already have the sample project you've tried, it will be helpful to provide it to me.

**Comment by nekrasov-andrii** [comment]
Hi @jsakamoto,
Today I found the reason why I couldn't manage theme changes for components.
I couldn’t understand why my service that tracks theme changes is always null.
Then I noticed that instead of “IFramePage” it is always rendered “IndexPage”.
Therefore, all my attempts to observable the change of current theme were fruitless.
I created a new project to find the problem, but everything worked fine in it, and the theme change tracking worked.
The reason why theme change observable didn't work on my main project was "BlazingStoryServerComponent".

![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/8e4851c3-e7de-4122-91b9-f1c31716209e)

The fact is that in my project there is an additional path in the form of the application name.
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/b6aae6f7-425f-4264-b495-060481d31528)

I copied your class and changed the code a little.
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/e4f4bb80-2f17-4960-bff5-b0d8b4df02ca)

And everything started to work.

Please fix this as soon as possible.

Here is my version of how I observable the theme change.
This is only example.
[StoryBook2.zip](https://github.com/jsakamoto/BlazingStory/files/15061533/StoryBook2.zip)


Kind regards, Andrii.

**Comment by jsakamoto** [comment]
@nekrasov-andrii Thank you for the detailed description of the problem. I'm investigating it now. However, I have an urgent matter, so please give me more days. Thank you for your patience.

**Comment by nekrasov-andrii** [comment]
Hi @jsakamoto,
This morning, I installed a new version of the "Blazing Story".
It works)
Thank you @jsakamoto!
