### ISSUE TITLE
Type or namespace could not be found. 

### ISSUE THREAD

**Issue by NathanVG** [jsakamoto/BlazingStory#32]
I'm trying to build a component library using a Razor Class Library. 

I set up blazing story like the docs specifiy, however whenever I try to run blazing story or build the solution I get the error that the type or namespace that is defined on line 1 of program.cs in my .stories project could not be found. 

I have changed the namespaces, removed the projects, started from scratch, renamed etc, all to no avail. 

Any ideas?

**Comment by jsakamoto** [comment]
Hi @NathanVG,
Could you share your project that is running into that problem? I'll look into it.

**Comment by NathanVG** [comment]
Updating Visual Studio 2022 and the SDK fixed this.
