### ISSUE TITLE
Hotkeys not working in the BlazingStory server

### ISSUE THREAD

**Issue by nekrasov-andrii** [jsakamoto/BlazingStory#41]
Hi @jsakamoto,

Hotkeys don't work
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/2e7e00cc-95be-41cf-8b8d-034415d6fe42)

An exception occurs after pressing any hotkey
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/1974c470-5600-46d4-b954-745eedbea046)

[StoryBookPreventDefault.zip](https://github.com/jsakamoto/BlazingStory/files/15263539/StoryBookPreventDefault.zip)

Kind regards,
Andrii

**Comment by jsakamoto** [comment]
Hi @nekrasov-andrii,
I released the fixed version, v.1.0.0 Preview 36, today.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.36#releasenotes-body-tab

Thank you for your reporting!
