### ISSUE TITLE
Property descriptions are not displayed if the component inherits from a generic type.

### ISSUE THREAD

**Issue by nekrasov-andrii** [jsakamoto/BlazingStory#43]
Hi @jsakamoto,

In my project I use the third-party library "[Syncfusion](https://blazor.syncfusion.com/documentation/introduction)".
Some components are inherited from the components of this library.
In the example I gave, two components are inherited from this library,
but if the component has a generic type, then the property description is not displayed.

Without generic type:
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/456023d5-1099-4666-9222-65f0eb4aedad)

With generic type:
![image](https://github.com/jsakamoto/BlazingStory/assets/60427587/0ab7f0d4-0ebe-4ff6-a62a-2bb143b6f1f5)

Is this expected behavior?

[StoryBookThirdPartyLibraries.zip](https://github.com/jsakamoto/BlazingStory/files/15286788/StoryBookThirdPartyLibraries.zip)

Kind regards,
Andrii

**Comment by jsakamoto** [comment]
Hi @nekrasov-andrii, Thank you again for your reporting!

Today, I released the fixed version, 1.0.0 Preview 37.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.37#releasenotes-body-tab

I believe that version fixed this issue. Would you try it out? Thanks!

**Comment by nekrasov-andrii** [comment]
Hi @jsakamoto,
Today I installed new version.
It works)
Thank you very much.

Kind regards,
Andrii
