### ISSUE TITLE
Error when referenced project wants to create multiple xml-files with the same name. 

### ISSUE THREAD

**Issue by AdamTrnkvist** [jsakamoto/BlazingStory#48]
Hi @jsakamoto
Apologies on the title, I'm not sure how to summarize the error. 

I updated BlazingStory today and received the following error:
````
Conflicting assets with the same target path '_framework/PdfSharp.Charting.xml'. For 'Build' assets 
'Identity: C:\Users\Adam\source\repos\Admin\src\StoryBook\bin\Debug\net7.0\wwwroot\_framework\PdfSharp.Charting.xml, SourceType: Computed, SourceId: StoryBook, ContentRoot: C:\Users\Adam\source\repos\Admin\src\StoryBook\bin\Debug\net7.0\wwwroot\, BasePath: /, RelativePath: _framework/PdfSharp.Charting.xml, AssetKind: Build, AssetMode: All, AssetRole: Primary, AssetRole: , AssetRole: , RelatedAsset: , AssetTraitName: BlazorWebAssemblyResource, AssetTraitValue: symbol, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: C:\Users\Adam\.nuget\packages\pdfsharp\1.50.5147\lib\net20\PdfSharp.Charting.xml' 
and 
'Identity: C:\Users\Adam\source\repos\Admin\src\StoryBook\bin\Debug\net7.0\wwwroot\_framework\PdfSharp.Charting.xml, SourceType: Computed, SourceId: StoryBook, ContentRoot: C:\Users\Adam\source\repos\Admin\src\StoryBook\bin\Debug\net7.0\wwwroot\, BasePath: /, RelativePath: _framework/PdfSharp.Charting.xml, AssetKind: Build, AssetMode: All, AssetRole: Primary, AssetRole: , AssetRole: , RelatedAsset: , AssetTraitName: BlazorWebAssemblyResource, AssetTraitValue: symbol, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: C:\Users\Adam\.nuget\packages\pdfsharp-migradoc\1.50.5147\lib\net20\PdfSharp.Charting.xml'.
C:\Program Files\dotnet\sdk\8.0.205\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets	475	
````

Upon investigation i found out that I get this error on versions above 22, so I checked the changed on github and found that version 23 introduces some new functionality to get XML Doc comments. This seems to cause a problem with PdfSharp and PdfSharp-MigraDoc since they both want to create an 'PdfSharp.Charting.xml'-file.

## Maybe fix suggestion

The following code is taken from the current main (BlazingStory/BlazingStory/Build/BlazingStory.targets) and I believe that this is what causes the problem:
![image](https://github.com/jsakamoto/BlazingStory/assets/22470548/77ba3c44-a9e4-47db-adac-1e72717ddc0c)

Is there any way to specify that xml-files can be overwritten if multiple files exist with the same name? 
If not, is there anything that can be done so I myself can extend the condition of excluded filenames.

Thanks

**Comment by jsakamoto** [comment]
@AdamTrnkvist Thank you for your reporting! The long title is not a matter at all. Rather, I am glad it is correctly explained.

In fact, this is an extremely edge case that conflicts with the XML document comment file name among different packages. But I'll try to manage to resolve this case.

**Comment by jsakamoto** [comment]
Hi @AdamTrnkvist,

Surprisingly, after some investigation, I found that the PDFsharp-MigraDoc package contains the exact same assemblies as those included in the PDFsharp package.

![Image](https://github.com/jsakamoto/BlazingStory/assets/95908/de96a126-f42f-47f1-9357-dca6f48b050b)

This kind of package distribution is really strange, and it is a bad practice.

Anyway, the PDFsharp-MigraDoc package contains everything that the PDFsharp package provides, so it is redundant to reference both of these packages from a single application.

Could you remove references to the PDFsharp package from your project? I believe that will make everything go well.

**Comment by AdamTrnkvist** [comment]
Sadly, I can't remove the PDFsharp reference since it's referenced in a local packade that's used in multiple products already. I just wanted to see if there was anything that could be done to BlazingStory to handle this. 

We are working on replacing the package that are referencing PDFsharp though, so I guess I just have to wait until that is done and then update BlazingStory.

Thanks, for looking into this, I really appreciate it.
