### ISSUE TITLE
Support for Complex Object Parameter Controls in Stories

### ISSUE THREAD

**Issue by cezar06** [jsakamoto/BlazingStory#52]
Currently, Blazor Story allows easy control of primitive types (int, bool, string, etc.) as parameters in the Controls section of a story. However, it doesn't provide a way to create or control more complex objects, such as custom classes or lists of objects.

I'd like to be able to create and modify instances of these classes, as well as lists of these objects, directly from the Controls section.

**Comment by WimVdSElia** [comment]
The issue already exists: [Issue](https://github.com/jsakamoto/BlazingStory/issues/13)
