### ISSUE TITLE
Stories are shown in a seemingly random order

### ISSUE THREAD

**Issue by mooski** [jsakamoto/BlazingStory#7]
Once you've implemented multiple stories, the order they display in within the sidebar is seemingly random, for example:

![image](https://github.com/jsakamoto/BlazingStory/assets/34440165/a7f17231-3ee4-4e9d-9a72-4ffdc073a8bf)

I'd expect them to be displayed in alphabetical order.

Is there logic to this order?

**Comment by jsakamoto** [comment]
@mooski Thank you for your feedback, and sorry that it is too late. Unfortunately, I'm too busy to handle issues in these weeks. But I'll handle this issue until the end of July. Thank you for your patience.

**Comment by jsakamoto** [comment]
@mooski 
I published the new version of "Blazing Story", v.1..0.0 Preview 9, which was improved to sort navigation items by their caption.

https://www.nuget.org/packages/BlazingStory/1.0.0-preview.9

Could you try it out?

**Comment by mooski** [comment]
That seems to work perfectly, thanks!
